#  basic data


{'basePrice': 1648.85,
 'change': 21.550000000000182,
 'checkINAV': False,
 'close': 0,
 'iNavValue': None,
 'intraDayHighLow': {'max': 1674.7, 'min': 1650.1, 'value': 1670.4},
 'lastPrice': 1670.4,
 'lowerCP': '1484.00',
 'open': 1650.1,
 'pChange': 1.3069715256087686,
 'pPriceBand': 'No Band',
 'previousClose': 1648.85,
 'upperCP': '1813.70',
 'vwap': 1666.13,
 'weekHighLow': {'max': 1674.7,
                 'maxDate': '23-Jan-2024',
                 'min': 1185.3,
                 'minDate': '17-Apr-2023',
                 'value': 1670.4}}





# all data


{'industryInfo': {'basicIndustry': 'Computers - Software & Consulting',
                  'industry': 'IT - Software',
                  'macro': 'Information Technology',
                  'sector': 'Information Technology'},
 'info': {'activeSeries': ['EQ'],
          'companyName': 'Infosys Limited',
          'debtSeries': [],
          'identifier': 'INFYEQN',
          'industry': 'COMPUTERS - SOFTWARE',
          'isCASec': False,
          'isDebtSec': False,
          'isDelisted': False,
          'isETFSec': False,
          'isFNOSec': True,
          'isSLBSec': True,
          'isSuspended': False,
          'isTop10': False,
          'isin': 'INE009A01021',
          'symbol': 'INFY',
          'tempSuspendedSeries': []},
 'metadata': {'industry': 'Computers - Software & Consulting',
              'isin': 'INE009A01021',
              'lastUpdateTime': '23-Jan-2024 11:20:46',
              'listingDate': '08-Feb-1995',
              'pdSectorInd': 'NIFTY '
              'IT                                          ',
              'pdSectorPe': 28.04,
              'pdSymbolPe': 28.04,
              'series': 'EQ',
              'status': 'Listed',
              'symbol': 'INFY'},
 'preOpenMarket': {'Change': 1.25,
                   'IEP': 1650.1,
                   'ato': {'buy': 62530, 'sell': 2664},
                   'atoBuyQty': 62530,
                   'atoSellQty': 2664,
                   'finalPrice': 1650.1,
                   'finalQuantity': 251604,
                   'lastUpdateTime': '23-Jan-2024 09:08:40',
                   'perChange': 0.07581041331837342,
                   'preopen': [{'buyQty': 0, 'price': 1484, 'sellQty': 56620},
                               {'buyQty': 0, 'price': 1485, 'sellQty': 1},
                               {'buyQty': 0,
                                'price': 1533.45,
                                'sellQty': 62901},
                               {'buyQty': 0, 'price': 1566.45,
                                'sellQty': 4368},
                               {'buyQty': 0,
                                'iep': True,
                                'price': 1650.1,
                                'sellQty': 0},
                               {'buyQty': 6, 'price': 1731.85,
                                'sellQty': 0},
                               {'buyQty': 50, 'price': 1800,
                                              'sellQty': 0},
                               {'buyQty': 10, 'price': 1801,
                                              'sellQty': 0},
                               {'buyQty': 229, 'price': 1813.7, 'sellQty': 0}],
                   'prevClose': 1648.85,
                   'totalBuyQuantity': 112945,
                   'totalSellQuantity': 115773,
                   'totalTradedVolume': 251604},
 'priceInfo': {'basePrice': 1648.85,
               'change': 20.75,
               'checkINAV': False,
               'close': 0,
               'iNavValue': None,
               'intraDayHighLow': {'max': 1674.7,
                                   'min': 1650.1,
                                   'value': 1669.6},
               'lastPrice': 1669.6,
               'lowerCP': '1484.00',
                          'open': 1650.1,
                          'pChange': 1.2584528610849985,
                          'pPriceBand': 'No Band',
                          'previousClose': 1648.85,
                          'upperCP': '1813.70',
                          'vwap': 1666.22,
                          'weekHighLow': {'max': 1674.7,
                                          'maxDate': '23-Jan-2024',
                                          'min': 1185.3,
                                          'minDate': '17-Apr-2023',
                                          'value': 1669.6}},
 'sddDetails': {'SDDAuditor': '-', 'SDDStatus': '-'},
 'securityInfo': {'boardStatus': 'Main',
                  'classOfShare': 'Equity',
                  'derivatives': 'Yes',
                  'faceValue': 5,
                  'issuedSize': 4150452781,
                  'sessionNo': '-',
                  'slb': 'Yes',
                  'surveillance': {'desc': None, 'surv': None},
                  'tradingSegment': 'Normal Market',
                  'tradingStatus': 'Active'}}
